myTuple = ("apple", 'banana', "cherry", 'kiwi', 'melon', 'mango', 'banana')
x = (5, 65, 78, 45, 2)
rev_x = reversed(x)
rev = reversed(myTuple)
# join = ''.join(myTuple)
print(tuple(rev))
print(tuple(rev_x))
# print(join)